arch:
  '*':
    # Salt configuration
    - salt-configuration

    # Base system configuration
    - kernel
    - fstab
    - firmware
    - bootloader

    # Higher level configuration
    - hostname
    - ntp
    - timezone
    - internet
    - ntfs
    - exfat
    - audio # Might need to do pacman -Sy pipewire-jack (to resolve conflict where pipewire replaces jack2)
    - yay
    - network-utils
    - hibernation # Warning, restarts login manager
    #- thunderbolt
    #- pam
    - polkit
    - fonts
    #- firewall
    #- power-management
    - bluetooth
    - display-manager
    - wireguard
    - printers
    - man
    - pagers
    
    # User configuration
    - users
    - sudoers

    - home-directories
    
    - bash
    - which
    - shell-profile
    - pacman

    #- user-service-manager
    #- xdg-autostart

  'pascal':
    # Higher level confifguration
    - backlight
    - fingerprint-reader
    - fingerprint-gui

    # Development environment configuration
    - ssh
    - git
    - salt-apply-script
    - alacritty
    - kitty
    - c
    - cmake
    - meson
    - uv
    - shellcheck
    - screen
    - kubectl
    - kustomize
    #- ncdu
    - containers
    - go
    - nodejs
    - flutter
    - terraform
    - tflint
    - infracost
    #- software-defined-radio
    - digitalocean-cli
    - godot
    #- dotnet
    #- ceph-client
    - dig
    - nmap
    - netcat
    - telnet
    #- insomnia
    - python
    - pyenv
    - pipenv
    - aws-cli
    - gcloud-cli
    - helm
    #- eksctl
    - java
    - android-sdk
    - apktool
    - salt-lint
    - jq
    - yq
    - gtk-dev
    - unreal-engine
    - httpie
    - s3cmd
    - wireshark
    - hugo
    - arduino
    - latex
    - talosctl
    - ipmitool
    - icedtea-web
    - buffalo
    - platformio
    - rsync
    - downgrade
    - xxd
    - kubectx
    - nx
    - gemini-cli
    - claude-code
    - qwen-code
    - vagrant
    - mkcert
    - libfreenect
    - caffeinate
    - fedify
    - deno
    - openai-codex
    - tree
    - cables
    - firebase

    # General tools configuration
    - gpg
    - trash-cli
    - htop
    - flatpak
    - flameshot
    - spell-check
    - qt
    - pkgfile
    - ncdu
    - modprobed-db
    
    # User interface configuration
    - vulkan
    #- wayland
    #- xdg-desktop-portal
    #- start-wayland-script
    - x11
    - xorg
    - wl-snip
    - rice
    - sway
    - hyprland
    - scrot
    - i3
    - gnome-keyring

    # Applications configuration
    #- links
    - firefox
    - geoclue # (Firefox geolocation)
    - avahi
    - librewolf
    - chrome
    - syncthing
    - blender
    #- emacs
    - doom-emacs
    - vscode
    - cursor-editor
    - signal
    - gimp
    - discord
    - openvpn
    - qbittorrent
    - k3s
    #- gnucash
    - youtube-dl
    - open-broadcaster-software
    - open-broadcaster-software-input-overlay
    - steam
    - steam-link
    #- tailscale
    - file-manager
    - ngrok
    - inkscape
    - vlc
    - mpv
    - anki
    - qgis
    - jetbrains
    - hidclient
    - go-swagger
    - openapi-generator
    - zoom
    - qemu
    - gns3
    - virtualbox
    - 7zip
    - rpi-imager
    - cockatrice
    - wine
    - ipmiview
    - iperf
    - software-defined-radio
    - chirp
    - gthumb
    - korganizer
    - evolution
    - strawberry-music-organizer
    - gpodder
    - libre-office
    - vdirsyncer
    - ollama
    - ollama-code
    - sdrtrunk
    - sdrpp
    - dsd-fme
    - kdeconnect
    - tailscale
    - screenkey
    - kdenlive

  'marcuse':
    # Base system configuration
    - amdgpu
    
    # General tools configuration
    - gpg
    - trash-cli
    - htop
    - nvtop
    - flatpak
    - flameshot
    - spell-check
    - qt
    - pkgfile
    - ncdu
    - modprobed-db
    - tree
    - jq
    - yq
    - dig
    - nmap
    - netcat
    - telnet
    - rsync
    - unzip
    - steam-locomotive

    # Development environment configuration
    - ssh
    - git
    - salt-apply-script
    - alacritty
    - kitty
    - c
    - cmake
    - meson

    # ... Development environments
    - gtk-dev
    #- uv
    #- shellcheck
    - screen
    - kubectl
    - kustomize
    - ncdu
    - containers
    #- go
    - nodejs
    #- flutter
    - terraform
    #- tflint
    #- infracost
    #- software-defined-radio
    #- digitalocean-cli
    #- godot
    #- dotnet
    #- ceph-client
    #- insomnia
    - python
    - pyenv
    - pipenv
    #- aws-cli
    #- gcloud-cli
    #- helm
    #- eksctl
    - java
    #- android-sdk
    #- apktool
    #- salt-lint
    #- unreal-engine
    #- httpie
    #- s3cmd
    #- wireshark
    #- hugo
    #- arduino
    #- latex
    #- talosctl
    #- ipmitool
    #- icedtea-web
    #- buffalo
    #- platformio
    #- downgrade
    #- xxd
    #- kubectx
    #- nx
    - gemini-cli
    - claude-code
    #- qwen-code
    - opencode
    #- vagrant
    #- mkcert
    #- libfreenect
    #- caffeinate
    #- fedify
    #- deno
    #- openai-codex
    #- cables
    #- firebase
    
    # User interface configuration
    - vulkan
    #- wayland
    #- xdg-desktop-portal
    #- start-wayland-script
    - x11
    - xorg
    #- wl-snip
    - rice
    #- sway
    #- hyprland
    - scrot
    - i3
    - gnome-keyring

    # Applications configuration
    #- links
    - firefox
    - geoclue # (Firefox geolocation)
    - avahi
    #- librewolf
    #- chrome
    #- syncthing
    #- blender
    #- emacs
    - doom-emacs
    #- vscode
    #- cursor-editor
    - signal
    - gimp
    - discord
    #- openvpn
    #- qbittorrent
    #- k3s
    #- gnucash
    #- youtube-dl
    #- open-broadcaster-software
    #- open-broadcaster-software-input-overlay
    - steam
    - steam-link
    - tailscale
    - file-manager
    #- ngrok
    #- inkscape
    #- vlc
    #- mpv
    #- anki
    #- qgis
    #- jetbrains
    #- hidclient
    #- go-swagger
    #- openapi-generator
    #- zoom
    #- qemu
    #- gns3
    #- virtualbox
    #- 7zip
    #- rpi-imager
    #- cockatrice
    #- wine
    #- ipmiview
    #- iperf
    #- software-defined-radio
    #- chirp
    #- gthumb
    #- korganizer
    #- evolution
    #- strawberry-music-organizer
    #- gpodder
    #- libre-office
    #- vdirsyncer
    #- ollama
    #- ollama-code
    #- sdrtrunk
    #- sdrpp
    #- dsd-fme
    #- kdeconnect
    #- tailscale
    #- screenkey
    #- kdenlive

  'benito':
    # Base system configuration
    - amdgpu
    - amd-rocm
    
    # General tools configuration
    - gpg
    - trash-cli
    - htop
    - nvtop
    - flatpak
    - flameshot
    - spell-check
    - qt
    - pkgfile
    - modprobed-db
    - tree
    - jq
    - yq
    - dig
    - nmap
    - netcat
    - telnet
    - rsync
    - unzip

    # Development environment configuration
    - ssh
    - git
    - salt-apply-script
    - alacritty
    - kitty
    - c
    - cmake
    - meson

    # ... Development environments
    - gtk-dev
    - uv
    #- shellcheck
    - screen
    #- kubectl
    - ncdu
    - containers
    #- go
    - nodejs
    #- flutter
    #- terraform
    #- tflint
    #- infracost
    #- software-defined-radio
    #- digitalocean-cli
    #- godot
    #- dotnet
    #- ceph-client
    #- insomnia
    - python
    - pyenv
    - pipenv
    #- aws-cli
    #- gcloud-cli
    #- helm
    #- eksctl
    - java
    #- android-sdk
    #- apktool
    #- salt-lint
    #- unreal-engine
    #- httpie
    #- s3cmd
    #- wireshark
    #- hugo
    #- arduino
    #- latex
    #- talosctl
    #- ipmitool
    #- icedtea-web
    #- buffalo
    #- platformio
    #- downgrade
    #- xxd
    #- kubectx
    #- nx
    - gemini-cli
    - claude-code
    - qwen-code
    #- vagrant
    #- mkcert
    #- libfreenect
    #- caffeinate
    #- fedify
    #- deno
    #- openai-codex
    #- cables
    #- firebase
    
    # User interface configuration
    - vulkan
    #- wayland
    #- xdg-desktop-portal
    #- start-wayland-script
    - x11
    - xorg
    #- wl-snip
    - rice
    #- sway
    #- hyprland
    - scrot
    - i3
    - gnome-keyring

    # Applications configuration
    #- links
    - firefox
    - geoclue # (Firefox geolocation)
    - avahi
    #- librewolf
    #- chrome
    #- syncthing
    #- blender
    #- emacs
    - doom-emacs
    #- vscode
    #- cursor-editor
    - signal
    - gimp
    - discord
    #- openvpn
    #- qbittorrent
    #- k3s
    #- gnucash
    #- youtube-dl
    #- open-broadcaster-software
    #- open-broadcaster-software-input-overlay
    - steam
    - steam-link
    - tailscale
    - file-manager
    #- ngrok
    #- inkscape
    #- vlc
    #- mpv
    #- anki
    #- qgis
    #- jetbrains
    #- hidclient
    #- go-swagger
    #- openapi-generator
    #- zoom
    #- qemu
    #- gns3
    #- virtualbox
    #- 7zip
    #- rpi-imager
    #- cockatrice
    #- wine
    #- ipmiview
    #- iperf
    #- software-defined-radio
    #- chirp
    #- gthumb
    #- korganizer
    #- evolution
    #- strawberry-music-organizer
    #- gpodder
    #- libre-office
    #- vdirsyncer
    #- ollama
    #- ollama-code
    #- sdrtrunk
    #- sdrpp
    #- dsd-fme
    #- kdeconnect
    #- tailscale
    #- screenkey
    #- kdenlive
